name: traveltool_flutter
description: A new Flutter module.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10 #网络请求
  connectivity: ^2.0.2 #网络检测
  cookie_jar: ^1.0.0 #cookie jar
  dio_cookie_manager: ^1.0.0 #cookie 管理
  json_serializable: ^3.5.1 #json
  build_runner: ^1.10.0
  cupertino_icons: ^0.1.2
  pull_to_refresh: ^1.5.6 #刷新列表组件
  cached_network_image: ^2.2.0+1 #加载网络图片
  fluttertoast: ^4.0.1 #Toast提示
  event_bus: ^1.1.1 #event_bus
  shared_preferences: ^0.5.12 #shared_preferences储存
  flutter_swiper: ^1.1.6 #轮播图
  flutter_inappwebview: ^4.0.0+4 #webView
  table_calendar: ^2.3.3 #日历
  intl: ^0.15.7 #国际
  data_plugin: ^0.0.16 #Bmob
  # horizontal_data_table: ^2.5.2 #表格
  # date_format: ^1.0.6
  # intl: ^0.15.8
  # crypto: ^2.0.6
  # flutter_refresh: ^0.0.2
  # gbk2utf8: ^0.0.1
  # fluwx_no_pay: ^2.2.0
  # share: ^0.6.3
  # flutter_html: ^0.10.4
  # convert: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: comflutter.simflutter.traveltool_flutter
    iosBundleIdentifier: comflutter.simflutter.traveltoolFlutter
  assets:
    - images/user/photo.jpg
    - images/user/login.png
    - images/user/no_login.png
    - images/user/splash.jpg
    - images/swiper/photo1.jpg
    - images/swiper/photo2.jpg
    - images/swiper/photo3.jpg
    - images/swiper/photo4.jpg
    - images/swiper/photo5.jpg
    - images/record/record_start.png
    - images/record/record_end.png
    - images/record/record_no_login.png
